version: '3.8'

services:
  web:
    build: .
    container_name: marketplace_frontend
    ports:
      - 8080:80
    volumes:
      - .:/app
    stdin_open: true
    tty: true
  nginx:
    image: nginx:alpine
    container_name: marketplace-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web